/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'salary' : null } |
  { 'other' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'transport' : null } |
  { 'utilities' : null };
export interface CategoryBreakdown {
  'salary' : bigint,
  'other' : bigint,
  'entertainment' : bigint,
  'food' : bigint,
  'transport' : bigint,
  'utilities' : bigint,
}
export interface MonthlySummary {
  'month' : bigint,
  'expenses' : bigint,
  'year' : bigint,
  'income' : bigint,
}
export interface Report {
  'categoryBreakdowns' : Array<CategoryBreakdown>,
  'monthlySummaries' : Array<MonthlySummary>,
}
export type Time = bigint;
export interface Transaction {
  'transactionType' : TransactionType,
  'date' : Time,
  'description' : string,
  'category' : Category,
  'amount' : bigint,
  'transactionId' : bigint,
}
export interface TransactionData {
  'transactionType' : TransactionType,
  'date' : Time,
  'description' : string,
  'category' : Category,
  'amount' : bigint,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTransaction' : ActorMethod<[TransactionData], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'exportTransactionsAsCsv' : ActorMethod<[Array<Transaction>], string>,
  'generateReport' : ActorMethod<[Time, Time], Report>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryStats' : ActorMethod<[Time, Time], CategoryBreakdown>,
  'getMonthlyStats' : ActorMethod<[bigint, bigint], MonthlySummary>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getTransactionsByCategory' : ActorMethod<[Category], Array<Transaction>>,
  'getTransactionsByType' : ActorMethod<[TransactionType], Array<Transaction>>,
  'getTransactionsInDateRange' : ActorMethod<[Time, Time], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[], Array<Transaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTransaction' : ActorMethod<[bigint, TransactionData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];