/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'salary' : IDL.Null,
  'other' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'transport' : IDL.Null,
  'utilities' : IDL.Null,
});
export const TransactionData = IDL.Record({
  'transactionType' : TransactionType,
  'date' : Time,
  'description' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Nat64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'date' : Time,
  'description' : IDL.Text,
  'category' : Category,
  'amount' : IDL.Nat64,
  'transactionId' : IDL.Nat,
});
export const CategoryBreakdown = IDL.Record({
  'salary' : IDL.Nat64,
  'other' : IDL.Nat64,
  'entertainment' : IDL.Nat64,
  'food' : IDL.Nat64,
  'transport' : IDL.Nat64,
  'utilities' : IDL.Nat64,
});
export const MonthlySummary = IDL.Record({
  'month' : IDL.Nat,
  'expenses' : IDL.Nat64,
  'year' : IDL.Nat,
  'income' : IDL.Nat64,
});
export const Report = IDL.Record({
  'categoryBreakdowns' : IDL.Vec(CategoryBreakdown),
  'monthlySummaries' : IDL.Vec(MonthlySummary),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([TransactionData], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'exportTransactionsAsCsv' : IDL.Func(
      [IDL.Vec(Transaction)],
      [IDL.Text],
      ['query'],
    ),
  'generateReport' : IDL.Func([Time, Time], [Report], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryStats' : IDL.Func([Time, Time], [CategoryBreakdown], ['query']),
  'getMonthlyStats' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlySummary], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactionsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsInDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTransaction' : IDL.Func([IDL.Nat, TransactionData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'salary' : IDL.Null,
    'other' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'transport' : IDL.Null,
    'utilities' : IDL.Null,
  });
  const TransactionData = IDL.Record({
    'transactionType' : TransactionType,
    'date' : Time,
    'description' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Nat64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'date' : Time,
    'description' : IDL.Text,
    'category' : Category,
    'amount' : IDL.Nat64,
    'transactionId' : IDL.Nat,
  });
  const CategoryBreakdown = IDL.Record({
    'salary' : IDL.Nat64,
    'other' : IDL.Nat64,
    'entertainment' : IDL.Nat64,
    'food' : IDL.Nat64,
    'transport' : IDL.Nat64,
    'utilities' : IDL.Nat64,
  });
  const MonthlySummary = IDL.Record({
    'month' : IDL.Nat,
    'expenses' : IDL.Nat64,
    'year' : IDL.Nat,
    'income' : IDL.Nat64,
  });
  const Report = IDL.Record({
    'categoryBreakdowns' : IDL.Vec(CategoryBreakdown),
    'monthlySummaries' : IDL.Vec(MonthlySummary),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([TransactionData], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'exportTransactionsAsCsv' : IDL.Func(
        [IDL.Vec(Transaction)],
        [IDL.Text],
        ['query'],
      ),
    'generateReport' : IDL.Func([Time, Time], [Report], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryStats' : IDL.Func([Time, Time], [CategoryBreakdown], ['query']),
    'getMonthlyStats' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlySummary],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactionsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsInDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTransaction' : IDL.Func([IDL.Nat, TransactionData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };