/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransactionData {
    transactionType: TransactionType;
    date: Time;
    description: string;
    category: Category;
    amount: bigint;
}
export interface CategoryBreakdown {
    salary: bigint;
    other: bigint;
    entertainment: bigint;
    food: bigint;
    transport: bigint;
    utilities: bigint;
}
export type Time = bigint;
export interface MonthlySummary {
    month: bigint;
    expenses: bigint;
    year: bigint;
    income: bigint;
}
export interface Report {
    categoryBreakdowns: Array<CategoryBreakdown>;
    monthlySummaries: Array<MonthlySummary>;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    transactionType: TransactionType;
    date: Time;
    description: string;
    category: Category;
    amount: bigint;
    transactionId: bigint;
}
export enum Category {
    salary = "salary",
    other = "other",
    entertainment = "entertainment",
    food = "food",
    transport = "transport",
    utilities = "utilities"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTransaction(data: TransactionData): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteTransaction(transactionId: bigint): Promise<void>;
    exportTransactionsAsCsv(transactions: Array<Transaction>): Promise<string>;
    generateReport(_startDate: Time, _endDate: Time): Promise<Report>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryStats(startDate: Time, endDate: Time): Promise<CategoryBreakdown>;
    getMonthlyStats(month: bigint, year: bigint): Promise<MonthlySummary>;
    getTransaction(transactionId: bigint): Promise<Transaction>;
    getTransactionsByCategory(category: Category): Promise<Array<Transaction>>;
    getTransactionsByType(transactionType: TransactionType): Promise<Array<Transaction>>;
    getTransactionsInDateRange(startDate: Time, endDate: Time): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTransactions(): Promise<Array<Transaction>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTransaction(transactionId: bigint, data: TransactionData): Promise<void>;
}
import type { Category as _Category, Time as _Time, Transaction as _Transaction, TransactionData as _TransactionData, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTransaction(arg0: TransactionData): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionData_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionData_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async exportTransactionsAsCsv(arg0: Array<Transaction>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportTransactionsAsCsv(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportTransactionsAsCsv(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateReport(arg0: Time, arg1: Time): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryStats(arg0: Time, arg1: Time): Promise<CategoryBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryStats(arg0, arg1);
            return result;
        }
    }
    async getMonthlyStats(arg0: bigint, arg1: bigint): Promise<MonthlySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyStats(arg0, arg1);
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByCategory(arg0: Category): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: TransactionType): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_TransactionType_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsInDateRange(arg0: Time, arg1: Time): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsInDateRange(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsInDateRange(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: TransactionData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_TransactionData_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_TransactionData_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    date: _Time;
    description: string;
    category: _Category;
    amount: bigint;
    transactionId: bigint;
}): {
    transactionType: TransactionType;
    date: Time;
    description: string;
    category: Category;
    amount: bigint;
    transactionId: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n17(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        category: from_candid_Category_n19(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salary: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    transport: null;
} | {
    utilities: null;
}): Category {
    return "salary" in value ? Category.salary : "other" in value ? Category.other : "entertainment" in value ? Category.entertainment : "food" in value ? Category.food : "transport" in value ? Category.transport : "utilities" in value ? Category.utilities : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n15(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionData_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionData): _TransactionData {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: TransactionType;
    date: Time;
    description: string;
    category: Category;
    amount: bigint;
    transactionId: bigint;
}): {
    transactionType: _TransactionType;
    date: _Time;
    description: string;
    category: _Category;
    amount: bigint;
    transactionId: bigint;
} {
    return {
        transactionType: to_candid_TransactionType_n3(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        transactionId: value.transactionId
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: TransactionType;
    date: Time;
    description: string;
    category: Category;
    amount: bigint;
}): {
    transactionType: _TransactionType;
    date: _Time;
    description: string;
    category: _Category;
    amount: bigint;
} {
    return {
        transactionType: to_candid_TransactionType_n3(_uploadFile, _downloadFile, value.transactionType),
        date: value.date,
        description: value.description,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    salary: null;
} | {
    other: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    transport: null;
} | {
    utilities: null;
} {
    return value == Category.salary ? {
        salary: null
    } : value == Category.other ? {
        other: null
    } : value == Category.entertainment ? {
        entertainment: null
    } : value == Category.food ? {
        food: null
    } : value == Category.transport ? {
        transport: null
    } : value == Category.utilities ? {
        utilities: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Transaction>): Array<_Transaction> {
    return value.map((x)=>to_candid_Transaction_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
